name: Deploy to New Prod Environment (Chareli)

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 330858616968.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO_SERVER: chareli-server-production-v1
  ECS_SERVICE: chareli-service-production-v1
  ECS_CLUSTER: chareli-ecs-cluster-production-v1
  ECS_TASK_DEFINITION: ./task-def.json
  CONTAINER_NAME: chareli-ecs-backend-production-server-v1
  IMAGE_TAG_SERVER_COMMIT: server-production-${{ github.sha }}
  IMAGE_TAG_SERVER_FIXED: latest

jobs:
  build-and-test:
    name: Build & Test Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Backend (Server) ---
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: Server/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./Server
        run: npm ci

      - name: Lint Backend
        working-directory: ./Server
        run: npm run lint
        continue-on-error: true

      - name: Test Backend
        working-directory: ./Server
        run: npm test
        continue-on-error: true

      # --- Frontend (Client) ---
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: Client/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./Client
        run: npm ci

      - name: Lint Frontend
        working-directory: ./Client
        run: npm run lint
        continue-on-error: true

      - name: Test Frontend
        working-directory: ./Client
        run: npm test
        continue-on-error: true

      - name: Build Frontend
        working-directory: ./Client
        env:
          VITE_API_URL: "https://api.chareli.reallygreattech.com"
          VITE_GAMES_CDN_URL: "https://pub-19e35e027f2848b39d57032cb6b2df46.r2.dev"
        run: npm run build

      - name: Archive Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./Client/dist

  deploy-backend:
    name: Deploy Backend to ECS
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::330858616968:role/chareli-production-v1-github-oidc-role
          aws-region: us-east-1

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        id: build-image
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_SERVER }}:${{ env.IMAGE_TAG_SERVER_COMMIT }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_SERVER }}:${{ env.IMAGE_TAG_SERVER_FIXED }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_SERVER }}:${{ env.IMAGE_TAG_SERVER_COMMIT }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          # wait-for-service-stability: true

  deploy-frontend:
    name: Deploy Frontend to Cloudflare Pages
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build-output

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.RGT_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.RGT_CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./frontend-build-output/ --project-name=chareli-prod
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  notify-discord:
    name: Notify Discord
    needs: [build-and-test, deploy-frontend, deploy-backend]
    #needs: [build-and-test, deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Generate Build Status
        id: build-status
        run: |
          if [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "build_msg=:white_check_mark: Build & Test PASSED" >> $GITHUB_OUTPUT
          else
            echo "build_msg=:x: Build & Test FAILED" >> $GITHUB_OUTPUT
          fi
      - name: Generate Backend Deploy Status
        id: backend-status
        run: |
          if [[ "${{ needs.deploy-backend.result }}" == "success" ]]; then
            echo "backend_msg=:white_check_mark: Backend deployment to ECS SUCCESSFUL" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.deploy-backend.result }}" == "skipped" ]]; then
            echo "backend_msg=:warning: Backend deployment SKIPPED" >> $GITHUB_OUTPUT
          else
            echo "backend_msg=:x: Backend deployment to ECS FAILED" >> $GITHUB_OUTPUT
          fi
      - name: Generate Frontend Deploy Status
        id: frontend-status
        run: |
          if [[ "${{ needs.deploy-frontend.result }}" == "success" ]]; then
            echo "frontend_msg=:white_check_mark: Frontend deployment to Cloudflare Pages SUCCESSFUL" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.deploy-frontend.result }}" == "skipped" ]]; then
            echo "frontend_msg=:warning: Frontend deployment SKIPPED" >> $GITHUB_OUTPUT
          else
            echo "frontend_msg=:x: Frontend deployment to Cloudflare Pages FAILED" >> $GITHUB_OUTPUT
          fi
      - name: Notify Discord
        if: always()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Chareli Dev Pipeline Bot
          message: |
            ğŸš€ **Chareli Production Deployment Summary**
            ğŸ”€ Branch: `${{ github.ref_name }}`
            ğŸ“„ Commit: `${{ github.event.head_commit.message }}` by `${{ github.actor }}`
            ğŸ—ï¸ Event: `${{ github.event_name }}`
            ğŸ§ª **Build & Test:** ${{ steps.build-status.outputs.build_msg }}
            ğŸ–¥ï¸ **Backend (ECS):** ${{ steps.backend-status.outputs.backend_msg }}
            ğŸŒ **Frontend (Cloudflare Pages):** ${{ steps.frontend-status.outputs.frontend_msg }}
            ğŸ”— [View Run on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ğŸ”— [View site here](https://dev.arcadesbox.reallygreattech.com)
