name: Deploy to Dev Environment

on:
  push:
    branches:
      - staging

permissions:
  packages: write
  contents: read
  id-token: write

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 330858616968.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPO: chareli-dev-repo
  S3_BUCKET: chareli-react-app-dev-ea15b364

jobs:
  build-test-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "npm"
          cache-dependency-path: Server/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run lint and Unit tests
        run: pnpm lint && pnpm test
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::330858616968:role/rgt-tickr-gha-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}
          tags: |
            type=raw,value=server-dev

      - name: Build and Push Backend Docker Image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
