name: Deploy to Staging Environment (arcadesbox)

on:
  push:
    branches: [main]
    tags:
      - "v*"

permissions:
  packages: write
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  ECR_REPO: ${{ vars.ECR_REPO }}
  ECS_SERVICE: ${{ vars.ECS_SERVICE }}
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER_NAME }}
  ECS_TASK_DEFINITION: ${{ vars.ECS_TASK_FAMILY }}
  CONTAINER_NAME: ${{ vars.ECS_CONTAINER_NAME }}

jobs:
  build-and-test:
    name: Build & Test Application
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'release' && 'production' || github.ref_name == 'dev' && 'development' || github.ref_name == 'main' && 'staging' || 'development' }}
    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Backend (Server) ---
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: Server/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./Server
        run: npm ci

      - name: Lint Backend
        working-directory: ./Server
        run: npm run lint
        continue-on-error: true

      - name: Test Backend
        working-directory: ./Server
        run: npm test
        continue-on-error: true

      # --- Frontend (Client) ---
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: Client/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./Client
        run: npm ci

      - name: Lint Frontend
        working-directory: ./Client
        run: npm run lint
        continue-on-error: true

      - name: Test Frontend
        working-directory: ./Client
        run: npm test
        continue-on-error: true

      - name: Build Frontend
        working-directory: ./Client
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL}}
          VITE_GAMES_CDN_URL: ${{ vars.VITE_GAMES_CDN_URL}}
          VITE_OFFICIAL_DOMAIN: ${{ vars.VITE_OFFICIAL_DOMAIN }}
          VITE_PAGES_DEV_DOMAIN: ${{ vars.VITE_PAGES_DEV_DOMAIN }}
          VITE_CLOUDFLARE_ZONE: ${{ vars.VITE_CLOUDFLARE_ZONE }}
        run: npm run build

      - name: Archive Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./Client/dist

  deploy-backend:
    name: Deploy Backend to ECS
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'release' && 'production' || github.ref_name == 'dev' && 'development' || github.ref_name == 'main' && 'staging' || 'development' }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug image paths
        run: |
          echo "ECR_REGISTRY= '${{ env.ECR_REGISTRY }}'"
          echo "ECR_REPO     = '${{ env.ECR_REPO }}'"
          echo "FULL IMAGE   = '${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}'"
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 476199653856.dkr.ecr.eu-central-1.amazonaws.com/arcadesbox-server-staging-v1
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

            type=ref,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/') }}
            type=sha,enable=${{ !startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  deploy-frontend:
    name: Deploy Frontend to Cloudflare Pages
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'release' && 'production' || github.ref_name == 'dev' && 'development' || github.ref_name == 'main' && 'staging' || 'development' }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build-output

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./frontend-build-output --project-name=${{ vars.PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  notify-discord:
    name: Notify Discord
    needs: [build-and-test, deploy-frontend, deploy-backend]
    environment: ${{ github.ref_name == 'release' && 'production' || github.ref_name == 'dev' && 'development' || github.ref_name == 'main' && 'staging' || 'development' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Generate Build Status
        id: build-status
        run: |
          if [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "build_msg=:white_check_mark: Build & Test PASSED" >> $GITHUB_OUTPUT
          else
            echo "build_msg=:x: Build & Test FAILED" >> $GITHUB_OUTPUT
          fi
      - name: Generate Backend Deploy Status
        id: backend-status
        run: |
          if [[ "${{ needs.deploy-backend.result }}" == "success" ]]; then
            echo "backend_msg=:white_check_mark: Backend deployment to ECS SUCCESSFUL" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.deploy-backend.result }}" == "skipped" ]]; then
            echo "backend_msg=:warning: Backend deployment SKIPPED" >> $GITHUB_OUTPUT
          else
            echo "backend_msg=:x: Backend deployment to ECS FAILED" >> $GITHUB_OUTPUT
          fi
      - name: Generate Frontend Deploy Status
        id: frontend-status
        run: |
          if [[ "${{ needs.deploy-frontend.result }}" == "success" ]]; then
            echo "frontend_msg=:white_check_mark: Frontend deployment to Cloudflare Pages SUCCESSFUL" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.deploy-frontend.result }}" == "skipped" ]]; then
            echo "frontend_msg=:warning: Frontend deployment SKIPPED" >> $GITHUB_OUTPUT
          else
            echo "frontend_msg=:x: Frontend deployment to Cloudflare Pages FAILED" >> $GITHUB_OUTPUT
          fi
      - name: Notify Discord
        if: always()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: ArcadesBox Release Pipeline Bot
          message: |
            ğŸš€ **ArcadesBox Production Deployment Summary(Client Account)**
            ğŸ”€ Branch: `${{ github.ref_name }}`
            ğŸ“„ Commit: `${{ github.event.head_commit.message }}` by `${{ github.actor }}`
            ğŸ—ï¸ Event: `${{ github.event_name }}`
            ğŸ§ª **Build & Test:** ${{ steps.build-status.outputs.build_msg }}
            ğŸ–¥ï¸ **Backend (ECS):** ${{ steps.backend-status.outputs.backend_msg }}
            ğŸŒ **Frontend (Cloudflare Pages):** ${{ steps.frontend-status.outputs.frontend_msg }}
            ğŸ”— [View Run on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ğŸ”— [View site here](${{ vars.APP_URL }})
